version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-smartcity:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-smartcity
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # internal / other containers
      - "29092:29092" # host access (Python producer, Spark, etc.)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Two listeners: one for other containers, one for host (Windows)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-smartcity:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka-smartcity
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-smartcity:9092"
      SERVER_PORT: 9000

  postgres:
    image: postgres:15
    container_name: postgres-traffic
    environment:
      POSTGRES_DB: smart_city_traffic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0956
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
